### ISSUE TITLE
setup.py 추가를 위한 파일구조 변경

### ISSUE THREAD

**Issue by jmg7173** [kosslab-kr/guider#10]
setup.py를 넣기 위해 파일 구조를 다음과 같이 변경시키겠습니다.

* `./guider` &rarr; `./guider/guider`
* `./guider.conf` &rarr; `./guider/guider.conf`
* `./guiderLib.c` &rarr; `./guider/guiderLib.c`
* `./guiderMod.c` &rarr; `./guider/guiderMod.c`
* `./guider.py` &rarr; `./guider/guider.py`
* `./guiderTest` &rarr; `./guider/guiderTest`
* `./Makefile` &rarr; `./guider/Makefile`

또한 setup.py 추가로 인해 setup.py로 설치시 나타나는 불필요한 폴더 및 파일을 gitignore에 추가하도록 하겠습니다.
* `build/`

**Comment by iipeace** [comment]
네, 멋지네요!
그런데 다른 분의 pull-request가 먼저
 merge 되어 guider.py가 변경되었고,
이로 인해 @jmg7173님의 commit에 대해 merge conflict 발생하니,
rebase 후 다시 pull-request 요청드립니다 :)

**Comment by jmg7173** [comment]
guider 원 프로젝트에서 travis CI 문제가 있어서 수정 후 다시 pull request 날리겠습니다.
폴더 구조가 바껴서 make가 동작하지 않아서 그런것 같은데 일단은 `cd guider`를 script에 추가해놓겠습니다.

**Comment by iipeace** [comment]
빌드 문제가 있었군요!

추가로 커밋 후 다시 pull-request 부탁드려요 :)



0.01s$ make && ./guider

make: *** No targets specified and no makefile found. Stop.

The command "make && ./guider" exited with 2.

**Comment by jmg7173** [comment]
@iipeace 
kosslab-kr에서 iipeace/guider에 pull request 날리면 merge conflict가 뜨는데
iipeace/guider에 어떻게 merge 해야할지 잘 모르겠네요 ㅠㅠ

**Comment by iipeace** [comment]
iipeace/guider를 fork하셔서 수정 후 push 및 pull-request 해보실래요?
repo가 제각각 수정되니 merge가 안될것 같습니다,
그래서 kosslab-kr과 iipeace repo에 동시 pull-request 하는게 sync가 맞지요 :)
일반적인 개발환경이 아니기에 좀 불편하셔도 콘트리뷰톤을 위해 양해 부탁드립니다 ㅠ

**Comment by jmg7173** [comment]
아..
제 fork되어있는 repo에서 iipeace/guider에 바로 pr 날리는건 conflict가 안뜨는데
그럼 바로 jmg7173/guider &rarr; iipeace/guider로 PR 날리겠습니다.
kosslab-kr/guider와 iipeace/guider의 sync는 어떻게 맞춰야할까요?
jmg7173/guider &rarr; iipeace/guider PR 후
kosslab-kr/guider &rarr; iipeace/guider PR을 하면 될까요?

**Comment by iipeace** [comment]
kosslab-kr에서 iipeace source fetch하여 update하는 방식으로 sync 맞췄습니다.

# git remote add upstream https://github.com/iipeace/guider
# git fetch upstream
# git pull upstream master
# git push
