### ISSUE TITLE
[시각화] [그라파나] 그래프 패널 꾸미기 1차

### ISSUE THREAD

**Issue by pyotel** [kosslab-kr/guider#21]

**Comment by pyotel** [comment]
![image](https://user-images.githubusercontent.com/11454375/45017325-4ecad780-b062-11e8-9952-bad90742d0bf.png)

**Comment by KangWooJin** [comment]
@pyotel 님 다른 host 추가해서 cpu 부분에 group by 시켜놓았습니다.

**Comment by pyotel** [comment]
현재 인플럭스에 올라오는 데이터들은 가시화 처리 완료 했으므로 일단 CLose

**Comment by pyotel** [comment]
@KangWooJin 수정하신거까지 하여 커밋 반영까지 하였습니다.
