### ISSUE TITLE
[시각화][그라파나] 표시할 데이터 선정하기 (1차)

### ISSUE THREAD

**Issue by pyotel** [kosslab-kr/guider#3]

**Comment by iipeace** [comment]
기본적으로 아래 내용에 대해 검토 요청드려요.
- process들의 cpu, memory 사용량
- running task 개수
- system 전체의 cpu 및 memory 사용량

아래 명령으로 guider에서 json 형식의 시스템 정보를 guider.report

**Comment by pyotel** [comment]
@iipeace 
적극 반영토록 하겠습니다
