### ISSUE TITLE
[시각화][그라파나] code convention

### ISSUE THREAD

**Issue by KangWooJin** [kosslab-kr/guider#34]
@pyotel 님 vim관련 설정 좀 올려주세요~ 보고 셋팅 하겠습니다.

셋팅 안하니깐 tap, space 같이 사용했다고 flake8이 경고하네요

**Comment by jmg7173** [comment]
보통은 스페이스만으로 4칸을 사용합니다. 제 세팅은 다음과 같습니다.
```vimrc
set ts=4
set sw=4
set bs=2
set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class

set autoindent
set expandtab
set smarttab
```

**Comment by jmg7173** [comment]
@KangWooJin 날린 pull request에 review들 달아놨습니다. 확인해주세요!

**Comment by pyotel** [comment]
guider/util/.vimrc 로 하도록 하겠습니다.
visual/grafana/.vimrc는 삭제하겠습니다
