### ISSUE TITLE
자동확장(Auto-Scaling) 기능

### ISSUE THREAD

**Issue by ghost** [kosslab-kr/guider#38]
AWS에 트래픽이 많아지면 인프라가 자동확장(Auto-Scaling) 되는 기능이 있습니다.

이 때 모니터링 시스템이 자동확장시에 확장되는 서버에 자동 설치 및 구성(CPU 사용률 임계치, Memory 사용률 임계치 등)이 되어 Manager 서버와 통신이 되야 실제 인프라 운영 조직에서 모니터링 시스템을 활용할 수 있습니다.

상용 모니터링 툴도 일부 지원되지 않는 것이 많은데 guider가 이런 기능 제공해줄 수 있는지 궁금해서
이슈로 등록합니다.

**Comment by iipeace** [comment]
guider에서 모니터링 기능 동작 중 특정 조건(CPU, 메모리, IO 임계치 초과 등) 만족 시 파일 생성으로 이벤트를 발생시키는 기능이 있습니다.
이벤트 발생 시 시스템  자원상태 정보도 리포트 해주기 때문에 이를 이용하시면 유용할 것 같습니다.
