### ISSUE TITLE
[기타] 깃허브 Assignee 설정 권한

### ISSUE THREAD

**Issue by pyotel** [kosslab-kr/guider#4]
깃허브 Assignee 설정 권한이 안되네요 그외에 레이블 등등도 
확인 부탁드립니다

**Comment by iipeace** [comment]
@pyotel 
추가로 운영자 권한 반영하였습니다.
확인 부탁드려요 :)

**Comment by pyotel** [comment]
@iipeace 
피스멘토님 이상하게도 여전히 안됩니다 ㅎㅎ
프로젝트도 생성하고 싶은데 안되네요

**Comment by pyotel** [comment]
@iipeace 
아 이제 잘되네요
인비테이션 승인을 안했군요 ㅋㅋ
