### ISSUE TITLE
Guider.report JSON형식을 Influx에 맞게 조정

### ISSUE THREAD

**Issue by pyotel** [kosslab-kr/guider#41]

**Comment by iipeace** [comment]
@pyotel 님,
어떤 방식으로 수정해야 할까요~?? :)

**Comment by pyotel** [comment]
@iipeace 
기존 원레벨이던 JSON 형식대로만 바꿀 수  있게끔 해주는 코드만 추가하면
influxDB로 데이터가 그대로 올라갈테니까요
그런식으로 바꿔줄 코드가 필요할거 같네요

**Comment by iipeace** [comment]
@pyotel
혹시 influxDB로 data 올리는 코드를 수정할순 없을까요~??
